// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function BrowseConfig():Promise<void>;

export function GetAppConfig():Promise<models.AppConfig>;

export function Greet(arg1:string):Promise<string>;

export function LaunchSSH(arg1:models.Connection):Promise<void>;

export function LaunchTerminal(arg1:string):Promise<string>;

export function SaveAppConfig(arg1:models.AppConfig):Promise<void>;
