// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetConnections():Promise<Array<models.Connection>>;

export function Greet(arg1:string):Promise<string>;

export function LaunchTerminal(arg1:string):Promise<string>;
