// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseConfig() {
  return window['go']['app']['App']['BrowseConfig']();
}

export function GetAppConfig() {
  return window['go']['app']['App']['GetAppConfig']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function LaunchSSH(arg1) {
  return window['go']['app']['App']['LaunchSSH'](arg1);
}

export function LaunchTerminal(arg1) {
  return window['go']['app']['App']['LaunchTerminal'](arg1);
}

export function SaveAppConfig(arg1) {
  return window['go']['app']['App']['SaveAppConfig'](arg1);
}
